In [1]:
import zipfile
with zipfile.ZipFile('/content/mushroom.zip', 'r') as zip_ref:
    zip_ref.extractall('/content')

In [2]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.feature_selection import SelectKBest, f_regression
from sklearn.impute import SimpleImputer
from sklearn.base import BaseEstimator, RegressorMixin
import numpy as np
from sklearn.model_selection import train_test_split

In [3]:
columns = ['class', 'cap-shape', 'cap-surface', 'cap-color', 'bruises', 'odor',
           'gill-attachment', 'gill-spacing', 'gill-size', 'gill-color',
           'stalk-shape', 'stalk-root', 'stalk-surface-above-ring',
           'stalk-surface-below-ring', 'stalk-color-above-ring',
           'stalk-color-below-ring', 'veil-type', 'veil-color', 'ring-number',
           'ring-type', 'spore-print-color', 'population', 'habitat']

df = pd.read_csv('agaricus-lepiota.data', names=columns)

In [4]:
df.head()

class cap-shape cap-surface cap-color bruises odor gill-attachment  \
0     p         x           s         n       t    p               f   
1     e         x           s         y       t    a               f   
2     e         b           s         w       t    l               f   
3     p         x           y         w       t    p               f   
4     e         x           s         g       f    n               f   

  gill-spacing gill-size gill-color  ... stalk-surface-below-ring  \
0            c         n          k  ...                        s   
1            c         b          k  ...                        s   
2            c         b          n  ...                        s   
3            c         n          n  ...                        s   
4            w         b          k  ...                        s   

  stalk-color-above-ring stalk-color-below-ring veil-type veil-color  \
0                      w                      w         p          w   
1                      w                      w         p          w   
2                      w                      w         p          w   
3                      w                      w         p          w   
4                      w                      w         p          w   

  ring-number ring-type spore-print-color population habitat  
0           o         p                 k          s       u  
1           o         p                 n          n       g  
2           o         p                 n          n       m  
3           o         p                 k          s       u  
4           o         e                 n          a       g  

[5 rows x 23 columns]

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8124 entries, 0 to 8123
Data columns (total 23 columns):
 #   Column                    Non-Null Count  Dtype 
---  ------                    --------------  ----- 
 0   class                     8124 non-null   object
 1   cap-shape                 8124 non-null   object
 2   cap-surface               8124 non-null   object
 3   cap-color                 8124 non-null   object
 4   bruises                   8124 non-null   object
 5   odor                      8124 non-null   object
 6   gill-attachment           8124 non-null   object
 7   gill-spacing              8124 non-null   object
 8   gill-size                 8124 non-null   object
 9   gill-color                8124 non-null   object
 10  stalk-shape               8124 non-null   object
 11  stalk-root                8124 non-null   object
 12  stalk-surface-above-ring  8124 non-null   object
 13  stalk-surface-below-ring  8124 non-null   object
 14  stalk-color-above-ring  

In [6]:
# Any missing values?
df.isnull().sum()

class                       0
cap-shape                   0
cap-surface                 0
cap-color                   0
bruises                     0
odor                        0
gill-attachment             0
gill-spacing                0
gill-size                   0
gill-color                  0
stalk-shape                 0
stalk-root                  0
stalk-surface-above-ring    0
stalk-surface-below-ring    0
stalk-color-above-ring      0
stalk-color-below-ring      0
veil-type                   0
veil-color                  0
ring-number                 0
ring-type                   0
spore-print-color           0
population                  0
habitat                     0
dtype: int64

In [7]:
for col in df.select_dtypes(include='object').columns:
    print(f"\nValue counts for '{col}':")
    print(df[col].value_counts())


Value counts for 'class':
class
e    4208
p    3916
Name: count, dtype: int64

Value counts for 'cap-shape':
cap-shape
x    3656
f    3152
k     828
b     452
s      32
c       4
Name: count, dtype: int64

Value counts for 'cap-surface':
cap-surface
y    3244
s    2556
f    2320
g       4
Name: count, dtype: int64

Value counts for 'cap-color':
cap-color
n    2284
g    1840
e    1500
y    1072
w    1040
b     168
p     144
c      44
u      16
r      16
Name: count, dtype: int64

Value counts for 'bruises':
bruises
f    4748
t    3376
Name: count, dtype: int64

Value counts for 'odor':
odor
n    3528
f    2160
s     576
y     576
a     400
l     400
p     256
c     192
m      36
Name: count, dtype: int64

Value counts for 'gill-attachment':
gill-attachment
f    7914
a     210
Name: count, dtype: int64

Value counts for 'gill-spacing':
gill-spacing
c    6812
w    1312
Name: count, dtype: int64

Value counts for 'gill-size':
gill-size
b    5612
n    2512
Name: count, dtype: int64

Value 

In [8]:
df.shape

(8124, 23)

In [9]:
y = LabelEncoder().fit_transform(df['class'])
X = df.drop(columns=['class', 'veil-type'])

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [11]:
X_train.head()

cap-shape cap-surface cap-color bruises odor gill-attachment  \
7873         k           s         e       f    s               f   
6515         x           s         n       f    f               f   
6141         f           y         e       f    y               f   
2764         f           f         n       t    n               f   
438          b           y         y       t    l               f   

     gill-spacing gill-size gill-color stalk-shape  ...  \
7873            c         n          b           t  ...   
6515            c         n          b           t  ...   
6141            c         n          b           t  ...   
2764            c         b          u           t  ...   
438             c         b          k           e  ...   

     stalk-surface-above-ring stalk-surface-below-ring stalk-color-above-ring  \
7873                        s                        k                      p   
6515                        k                        s                      w   
6141                        s                        s                      p   
2764                        s                        s                      g   
438                         s                        s                      w   

     stalk-color-below-ring veil-color ring-number ring-type  \
7873                      w          w           o         e   
6515                      w          w           o         e   
6141                      w          w           o         e   
2764                      p          w           o         p   
438                       w          w           o         p   

     spore-print-color population habitat  
7873                 w          v       d  
6515                 w          v       p  
6141                 w          v       l  
2764                 n          v       d  
438                  n          n       m  

[5 rows x 21 columns]

In [12]:
y_train[:10]

array([1, 1, 1, 0, 0, 1, 0, 0, 1, 1])

In [13]:
class mymlr:

  def __init__(self):
     self.m = None
     self.b = None

  def fit(self, X_train, y_train):
    X_train = np.insert(X_train, 0, 1, axis=1)

    betas = np.linalg.inv(np.dot(X_train.T, X_train)).dot(X_train.T).dot(y_train)
    self.m, self.b = betas[1:], betas[0]
    print(betas)

  def predict(self, X_test):
    y_pred = np.dot(X_test, self.m) + self.b
    return y_pred

In [14]:
class MySLRWrapper(BaseEstimator, RegressorMixin):
    def __init__(self):
        self.model = None

    def fit(self, X, y):
        X = X.reshape(-1, 1) if X.ndim == 1 else X
        self.model = mymlr()
        self.model.fit(X, y)
        return self

    def predict(self, X):
        X = X.reshape(-1, 1) if X.ndim == 1 else X
        return self.model.predict(X)

In [15]:
preprocessor = ColumnTransformer([
    ('cat', Pipeline(steps=[
        ('imputer', SimpleImputer(strategy='most_frequent')),
        ('onehot', OneHotEncoder(sparse_output=False, handle_unknown='ignore', drop='first'))
    ]), X.columns)
])

In [16]:
pipe = Pipeline([
    ('preprocessor', preprocessor),
    ('select', SelectKBest(score_func=f_regression, k=5)),
    ('model', MySLRWrapper())
])

In [17]:
pipe.fit(X, y)

[ 0.7384089   0.18268891 -0.57348601  0.10099616  0.04291677 -0.19975463]


Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('cat',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('onehot',
                                                                   OneHotEncoder(drop='first',
                                                                                 handle_unknown='ignore',
                                                                                 sparse_output=False))]),
                                                  Index(['cap-shape', 'cap-surface', 'cap-color', 'bruises', 'odor',
       'gill-attachment', 'gill-spacing', 'gill-size', 'gill-color',
       'stalk-shape', 'stalk-root', 'stalk-surface-above-ring',
       'stalk-surface-below-ring', 'stalk-color-above-ring',
       'stalk-color-below-ring', 'veil-color', 'ring-number', 'ring-type',
       'spore-print-color', 'population', 'habitat'],
      dtype='object'))])),
                ('select',
                 SelectKBest(k=5,
                             score_func=<function f_regression at 0x78c45e838400>)),
                ('model', MySLRWrapper())])

In [18]:
# Get feature names from preprocessor
feature_names = pipe.named_steps['preprocessor'].get_feature_names_out()

# Get mask of selected features
mask = pipe.named_steps['select'].get_support()

# Apply mask to feature names
selected_features = feature_names[mask]
print("Selected features:", selected_features)

Selected features: ['cat__odor_f' 'cat__odor_n' 'cat__stalk-surface-above-ring_k'
 'cat__stalk-surface-below-ring_k' 'cat__ring-type_p']


In [19]:
y_pred = pipe.predict(X_test)

/usr/local/lib/python3.12/dist-packages/sklearn/pipeline.py:62: FutureWarning: This Pipeline instance is not fitted yet. Call 'fit' with appropriate arguments before using other methods such as transform, predict, etc. This will raise an error in 1.8 instead of the current warning.
  warnings.warn(


In [20]:
from sklearn.metrics import mean_squared_error, r2_score

In [21]:
y_pred = pipe.predict(X_test)
print("MSE:", mean_squared_error(y_test, y_pred))
print("R²:", r2_score(y_test, y_pred))

MSE: 0.07018075852081793
R²: 0.7188808307484311


/usr/local/lib/python3.12/dist-packages/sklearn/pipeline.py:62: FutureWarning: This Pipeline instance is not fitted yet. Call 'fit' with appropriate arguments before using other methods such as transform, predict, etc. This will raise an error in 1.8 instead of the current warning.
  warnings.warn(


In [22]:
from sklearn.linear_model import LinearRegression
pipe = Pipeline([
    ('preprocessor', preprocessor),
    ('select', SelectKBest(score_func=f_regression, k=5)),
    ('model', LinearRegression())
])
pipe.fit(X_train, y_train)
# Get feature names from preprocessor
feature_names = pipe.named_steps['preprocessor'].get_feature_names_out()

# Get mask of selected features
mask = pipe.named_steps['select'].get_support()

# Apply mask to feature names
selected_features = feature_names[mask]
print("Selected features:", selected_features)
y_pred = pipe.predict(X_test)
print("MSE:", mean_squared_error(y_test, y_pred))
print("R²:", r2_score(y_test, y_pred))

Selected features: ['cat__odor_f' 'cat__odor_n' 'cat__gill-size_n'
 'cat__stalk-surface-above-ring_k' 'cat__stalk-surface-below-ring_k']
MSE: 0.051296714826241964
R²: 0.7945235964782257


In [23]:
y_pred_class = (y_pred >= 0.5).astype(int)
from sklearn.metrics import accuracy_score, confusion_matrix

print("Accuracy:", accuracy_score(y_test, y_pred_class))
print("Confusion matrix:\n", confusion_matrix(y_test, y_pred_class))


Accuracy: 0.9704615384615385
Confusion matrix:
 [[816  27]
 [ 21 761]]
